
name: CI/CD Pipeline

on:
  push:
    branches:
    - main
    paths:
    - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #Setting up environment
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Setup
      uses: docker/setup-buildx-action@v2

    - name: Docker Credentials
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker tag
      id: version
      run: |
        VERSION=v$(date +"%Y%m%d%H%M%S")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # Build the Docker Image
    # give here docker hub user-name
    - name: Build Docker Image
      run: |
        docker build -t asish915/ci-cd-terraform:${{ env.VERSION }} . 

    # Push the Docker Image
    - name: Push Docker Image
      run: |
        docker push asish915/ci-cd-terraform:${{ env.VERSION }}

    # UPdate the K8s Manifest Files
    - name: Update K8s Manifests
      run: |
        cat deploy/deployment.yaml
        sed -i "s|image: asish915/ci-cd-terraform:.*|image: asish915/ci-cd-terraform:${{ env.VERSION }}|g" deploy/deployment.yaml
        cat deploy/deployment.yaml

    # tfsec scanning
    - name: tfsec scan
      uses: aquasecurity/tfsec-action@v1.0.0

    # Trivy scanning
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/your_image:latest'

    # Deploy sealed-secrets
    - name: Deploy Sealed Secret
      run: |
        kubectl apply -f sealed-secrets/sealed-secret.yaml

    # Update Github
    - name: Commit the changes
      run: |
        git config --global user.email "<>"
        git config --global user.name "GitHub Actions Bot"
        git checkout main
        git add deploy/deployment.yaml
        git commit -m "Update deploy.yaml with new image version - ${{ env.VERSION }}"
        git push origin main